verify uniqueness of the session name

diff --git a/tmuxgo b/tmuxgo
--- a/tmuxgo
+++ b/tmuxgo
@@ -25,6 +25,14 @@ function startSession {
 
   name=${nameArg:-$name}
 
+  # ensure session name is unic
+  sessions=`tmux ls -F '#{session_name}'`
+  if [[ $sessions == *"$name"* ]]
+  then
+    >&2 echo "the session name $name is already used!"
+    return 1;
+  fi
+
   # Location if ~ is part of the path
   tmux new-session -d -c $location -n $windowName -s $name
 
@@ -59,9 +67,14 @@ function addWindow {
 }
 
 function attachSession {
+  unset TMUX;
   tmux attach -t $1
 }
 
-session=`startSession '' $NAME`
+session=`startSession '' $NAME` || {
+  echo 'Failed to init root session, exiting'
+  exit
+}
+
 addWindows '' $session
 attachSession $session
